"""
Autogenerated. Do not edit!
Use make_enum.py instead.
"""
from enum import IntEnum

class SampleFormat(IntEnum):
    """
    Wraps the Sample Formats
    File: /home/pippolo84/Progetti/pyrana/tools/samplefmt_tmp.h
    SHA-1: fd8c0c10256909ce67c45dbbed5ead599180b348
    """
    AV_SAMPLE_FMT_NONE = -1
    AV_SAMPLE_FMT_U8 = 0
    AV_SAMPLE_FMT_S16 = 1
    AV_SAMPLE_FMT_S32 = 2
    AV_SAMPLE_FMT_FLT = 3
    AV_SAMPLE_FMT_DBL = 4
    AV_SAMPLE_FMT_U8P = 5
    AV_SAMPLE_FMT_S16P = 6
    AV_SAMPLE_FMT_S32P = 7
    AV_SAMPLE_FMT_FLTP = 8
    AV_SAMPLE_FMT_DBLP = 9
    AV_SAMPLE_FMT_NB = 10
